project:
  type: website
  output-dir: docs

lang: en

website:
  title: "SCGIS Vancouver"
  favicon: "img/home/favicon.jpg"
  navbar:
    search: true
    pinned: false
    left:
      - href: index.qmd
        text: Home
      - resources.qmd
      - about.qmd
      - events.qmd
    tools:
      - icon: envelope
        href: mailto:scgis.canada.vancouver@gmail.com
        text: "Email the chapter representatives"
      - icon: instagram
        href: https://instagram.com/scgis.vancouver
        text: "Follow us on Instgram"
      - icon: github
        href: https://github.com/scgis-canada-vancouver
        text: "Follow our Github organization"
      - icon: linkedin
        href: https://www.linkedin.com/company/scgis-canada-vancouver
        text: Follow us on Linkedin

format:
  html:
    theme:
      - brite
    css: styles.css
    toc: false
    toc-location: left



