project:
  type: website
  output-dir: docs
  resources:
    - CNAME.txt

lang: en

website:
  title: "SCGIS Vancouver"
  favicon: "img/home/favicon.png"
  navbar:
    search: true
    pinned: false
    left:
      - href: index.qmd
        text: Home
      - text: "Resources"
        menu:
        - href: data_portals.qmd
          text: "Data Portals"
        - href: cons_env_hubs.qmd
          text: "Conservation & Environmental Hubs"
        - href: publications_news.qmd
          text: "Publications & News"
      - about.qmd
      - text: "Events"
        menu:
        - href: upcoming_events.qmd
          text: "Upcoming Events"
        - href: past_events.qmd
          text: "Past Events"
    tools:
      - icon: envelope
        href: mailto:scgis.canada.vancouver@gmail.com
        text: "Email the chapter representatives"
      - icon: instagram
        href: https://instagram.com/scgis.vancouver
        text: "Follow us on Instgram"
      - icon: github
        href: https://github.com/scgis-canada-vancouver
        text: "Follow our Github organization"
      - icon: linkedin
        href: https://www.linkedin.com/company/scgis-canada-vancouver
        text: Follow us on Linkedin
    

format:
  html:
    theme:
      - brite
    css: styles.css
    toc: false
    toc-location: left



